name: OSS 
on:
  push: 
    branches: 
      - main
jobs:
  docsearch:
    runs-on: ubuntu-latest
    container:
      image: algolia/docsearch-scraper
      env:
        APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
        API_KEY: ${{ secrets.API_KEY }}
      options: -e "CONFIG=$(cat ./docSearchConfig.json)" 
    steps:
    - name: Checkout
      uses: actions/checkout@main
    # - uses: addnab/docker-run-action@v3
    #   with:
    #     image: algolia/docsearch-scraper
    #     options: -v ${{ github.workspace }}:/docsearch -e APPLICATION_ID=${{ secrets.APPLICATION_ID }} -e API_KEY=${{ secrets.API_KEY }} -e "CONFIG=$(cat /docsearch/docSearchConfig.json)"
    
  